export default {
  BOKA_TID: 'BOKA_TID',
  READ_MORE_SERVICES: 'READ_MORE_SERVICES',
  READ_MORE_PROJECTS: 'READ_MORE_PROJECTS',
  READ_MORE_CLIENTS: 'READ_MORE_CLIENTS',
  CHANGE_INPUT_TEXT: 'CHANGE_INPUT_TEXT',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM'

};
